In [1]:
#### ------------------------------------------------------------------------------------------
#### author: Ranjan Barman, date: Jun 2, 2025
#### Mapped CPTAC HoverNet Immune-Only NPIFs (Top 25% tiles) to TCGA_BRCA subtype status
#### --------------------------------------------------------------------------------------------

import os
import pandas as pd

# Set working directory
_wpath_ = "/data/Lab_ruppin/Ranjan/HnE/"
os.chdir(_wpath_)
print(f"Working directory: {_wpath_}\n")

# Define dataset name and paths
dataset_name = "CPTAC_BRCA"

# File paths
CPTAC_BRCA_ImmuneOnly_NPIFs_file = f"{dataset_name}/HoverNet/outputs/CPTAC_BRCA_HoverNet_ImmuneOnly_NPIFs_Filtered_Tiles_Top25Q.csv"
CPTAC_subtypes_file = "/data/Lab_ruppin/dhrubas2/HnE/CPTAC_BRCA/processed/CPTAC_BRCA_clinical_data_summary_matched.tsv"

# Load the immune-only NPIFs (top 25% tile) data
CPTAC_BRCA_ImmuneOnly_NPIFs = pd.read_csv(CPTAC_BRCA_ImmuneOnly_NPIFs_file)

# Drop unnecessary tile count columns
CPTAC_BRCA_ImmuneOnly_NPIFs.drop(columns=["Total_Tiles", "Filtered_Tiles"], inplace=True)

# Remove trailing spaces from column names
CPTAC_BRCA_ImmuneOnly_NPIFs.columns = CPTAC_BRCA_ImmuneOnly_NPIFs.columns.str.strip()

# Load the clinical subtype data
CPTAC_subtypes_data = pd.read_table(CPTAC_subtypes_file, sep="\t")
CPTAC_subtypes_data = CPTAC_subtypes_data[["Patient_ID", "HER2_status", "PR_status", "ER_status"]]
CPTAC_subtypes_data = CPTAC_subtypes_data.rename(columns={
    "HER2_status": "HER2_Status",
    "PR_status": "PR_Status",
    "ER_status": "ER_Status"
})
CPTAC_subtypes_data["Patient_ID"] = CPTAC_subtypes_data["Patient_ID"].astype(str).str.zfill(3)

CPTAC_BRCA_ImmuneOnly_NPIFs
CPTAC_subtypes_data

Working directory: /data/Lab_ruppin/Ranjan/HnE/

    Patient_ID HER2_Status PR_Status ER_Status
0      01BR001    Negative  Negative  Negative
1      01BR008         NaN       NaN       NaN
2      01BR009         NaN  Negative  Negative
3      01BR010         NaN  Negative  Negative
4      01BR015    Negative  Positive  Positive
..         ...         ...       ...       ...
114    21BR001         NaN  Negative  Negative
115    21BR002         NaN  Positive  Positive
116    21BR010    Negative  Positive  Positive
117    22BR005    Positive  Positive  Positive
118    22BR006    Negative  Positive  Positive

[119 rows x 4 columns]

In [2]:
# Print debug info
print("Patient_IDs from CPTAC_BRCA_HoverNet_ImmuneOnly_NPIFs (Total: {}):".format(len(CPTAC_BRCA_ImmuneOnly_NPIFs)))
print(CPTAC_BRCA_ImmuneOnly_NPIFs["Patient_ID"].unique())
print("\nPatient IDs from CPTAC_subtypes_data (Total: {}):".format(len(CPTAC_subtypes_data)))
print(CPTAC_subtypes_data["Patient_ID"].unique())

# Find mismatches
slide_names = set(CPTAC_BRCA_ImmuneOnly_NPIFs["Patient_ID"])
patient_ids = set(CPTAC_subtypes_data["Patient_ID"])
non_matching_slides = slide_names - patient_ids
non_matching_patients = patient_ids - slide_names

print("\nImmune-only NPIFs (Top 25% tiles) with no matching Patient_ID:")
print(non_matching_slides)
print("\nSubtype entries with no matching NPIFs:")
print(non_matching_patients)

Patient_IDs from CPTAC_BRCA_HoverNet_ImmuneOnly_NPIFs (Total: 198):
['01BR001' '01BR002' '01BR003' '01BR004' '01BR005' '01BR006' '01BR007'
 '01BR008' '01BR009' '01BR010' '01BR011' '01BR012' '01BR013' '01BR014'
 '01BR015' '01BR016' '01BR017' '01BR018' '01BR019' '01BR020' '01BR021'
 '01BR022' '01BR023' '01BR024' '01BR025' '01BR026' '01BR027' '01BR028'
 '01BR029' '01BR030' '01BR031' '01BR032' '01BR033' '01BR034' '01BR039'
 '01BR040' '01BR041' '01BR042' '01BR043' '03BR002' '03BR004' '03BR005'
 '03BR006' '03BR008' '03BR009' '03BR010' '03BR011' '03BR012' '03BR013'
 '03BR014' '05BR001' '05BR002' '05BR003' '05BR004' '05BR005' '05BR009'
 '05BR010' '05BR015' '05BR016' '05BR019' '05BR022' '05BR024' '05BR026'
 '05BR029' '05BR031' '05BR032' '05BR033' '05BR038' '05BR040' '05BR042'
 '05BR043' '05BR044' '05BR045' '06BR003' '06BR005' '06BR006' '06BR009'
 '06BR014' '09BR001' '09BR002' '09BR004' '09BR005' '09BR007' '11BR003'
 '11BR004' '11BR005' '11BR006' '11BR009' '11BR010' '11BR011' '11BR012'
 '11BR013' '11BR014' '11BR015' '11BR016' '11BR017' '11BR018' '11BR019'
 '11BR020' '11BR021' '11BR022' '11BR023' '11BR024' '11BR025' '11BR027'
 '11BR028' '11BR029' '11BR030' '11BR031' '11BR032' '11BR033' '11BR034'
 '11BR035' '11BR036' '11BR037' '11BR038' '11BR040' '11BR041' '11BR042'
 '11BR043' '11BR044' '11BR047' '11BR048' '11BR049' '11BR050' '11BR051'
 '11BR052' '11BR053' '11BR054' '11BR055' '11BR056' '11BR057' '11BR058'
 '11BR059' '11BR060' '11BR069' '11BR072' '11BR073' '11BR074' '11BR075'
 '11BR076' '11BR077' '11BR078' '11BR079' '11BR080' '13BR003' '13BR004'
 '13BR009' '14BR002' '14BR005' '14BR007' '14BR008' '14BR011' '14BR012'
 '14BR014' '14BR020' '14BR023' '15BR001' '15BR002' '15BR003' '15BR004'
 '15BR011' '16BR012' '18BR001' '18BR002' '18BR003' '18BR004' '18BR005'
 '18BR006' '18BR007' '18BR008' '18BR009' '18BR010' '18BR016' '18BR017'
 '18BR019' '18BR020' '20BR001' '20BR002' '20BR003' '20BR004' '20BR005'
 '20BR006' '20BR007' '20BR008' '21BR001' '21BR002' '21BR003' '21BR005'
 '21BR010' '22BR001' '22BR002' '22BR003' '22BR005' '22BR006' '22BR007'
 '22BR008' '27BR002']

Patient IDs from CPTAC_subtypes_data (Total: 119):
['01BR001' '01BR008' '01BR009' '01BR010' '01BR015' '01BR017' '01BR018'
 '01BR020' '01BR023' '01BR025' '01BR026' '01BR027' '01BR030' '01BR031'
 '01BR032' '01BR033' '01BR040' '01BR042' '01BR043' '03BR002' '03BR004'
 '03BR006' '03BR010' '03BR011' '03BR013' '05BR001' '05BR003' '05BR004'
 '05BR005' '05BR009' '05BR016' '05BR026' '05BR029' '05BR038' '05BR042'
 '05BR043' '05BR044' '05BR045' '06BR003' '06BR005' '06BR006' '06BR014'
 '09BR001' '09BR004' '09BR005' '09BR007' '11BR003' '11BR004' '11BR006'
 '11BR009' '11BR010' '11BR011' '11BR012' '11BR013' '11BR014' '11BR015'
 '11BR016' '11BR017' '11BR018' '11BR019' '11BR020' '11BR022' '11BR023'
 '11BR024' '11BR025' '11BR027' '11BR028' '11BR030' '11BR031' '11BR032'
 '11BR036' '11BR038' '11BR040' '11BR042' '11BR043' '11BR044' '11BR047'
 '11BR049' '11BR050' '11BR051' '11BR053' '11BR054' '11BR055' '11BR056'
 '11BR058' '11BR059' '11BR060' '11BR072' '11BR073' '11BR074' '11BR075'
 '11BR080' '13BR009' '14BR005' '14BR008' '14BR014' '15BR003' '16BR012'
 '18BR002' '18BR003' '18BR004' '18BR006' '18BR007' '18BR009' '18BR010'
 '18BR016' '18BR017' '18BR019' '20BR001' '20BR002' '20BR005' '20BR006'
 '20BR007' '20BR008' '21BR001' '21BR002' '21BR010' '22BR005' '22BR006']

Immune-only NPIFs (Top 25% tiles) with no matching Patient_ID:
{'05BR019', '11BR079', '18BR001', '11BR021', '18BR008', '15BR011', '05BR010', '01BR028', '11BR033', '01BR029', '18BR005', '01BR041', '01BR006', '22BR007', '01BR024', '01BR022', '01BR039', '05BR015', '18BR020', '11BR057', '11BR035', '11BR077', '11BR048', '03BR009', '01BR019', '01BR021', '03BR012', '13BR004', '01BR013', '21BR005', '11BR069', '11BR005', '09BR002', '14BR023', '05BR024', '03BR005', '22BR002', '11BR029', '11BR052', '01BR012', '14BR007', '03BR014', '01BR034', '14BR011', '05BR002', '11BR034', '01BR003', '01BR011', '15BR001', '05BR022', '11BR041', '14BR002', '06BR009', '01BR005', '14BR020', '20BR004', '05BR033', '01BR016', '01BR002', '22BR008', '11BR076', '13BR003', '05BR040', '01BR004', '22BR001', '01BR014', '15BR004', '20BR003', '11BR078', '11BR037', '05BR031', '14BR012', '27BR002', '15BR002', '05BR032', '21BR003', '22BR003', '01BR007', '03BR008'}

Subtype entries with no matching NPIFs:
set()

In [3]:
# Merge NPIFs with subtype labels
merged_df = pd.merge(CPTAC_subtypes_data, CPTAC_BRCA_ImmuneOnly_NPIFs, on='Patient_ID', how="inner")

# Define output folder and file name
output_path = f"{dataset_name}/outputs/HoverNet/Subtypes/"
os.makedirs(output_path, exist_ok=True)
file_name = "HoverNet_ImmuneOnly_NPIFs_CPTAC_BRCA_Mapped_BRCA_Status_Filtered_Tiles_Top25Q.csv"
output_file = os.path.join(output_path, file_name)

# Save the result
merged_df.to_csv(output_file, index=False)
print(f"Mapped immune-only NPIF (Top 25%) data saved to: {output_file}")
print("Done!")

merged_df

Mapped immune-only NPIF (Top 25%) data saved to: CPTAC_BRCA/outputs/HoverNet/Subtypes/HoverNet_ImmuneOnly_NPIFs_CPTAC_BRCA_Mapped_BRCA_Status_Filtered_Tiles_Top25Q.csv
Done!

,Patient_ID,HER2_Status,PR_Status,ER_Status,Mean Area,Mean Major Axis,Mean Minor Axis,Mean Perimeter,Mean Eccentricity,Mean Circularity,Std Area,Std Major Axis,Std Minor Axis,Std Perimeter,Std Eccentricity,Std Circularity
0,01BR001,Negative,Negative,Negative,7.790775,3.835177,2.743594,10.900192,0.657119,0.788475,3.617815,0.959479,0.636387,2.606768,0.145975,0.068995
1,01BR008,NaN,NaN,NaN,6.750799,3.528689,2.564946,10.088011,0.642748,0.801209,3.171454,0.888279,0.580125,2.464665,0.144146,0.071469
2,01BR009,NaN,Negative,Negative,6.781093,3.578427,2.567401,10.228782,0.656285,0.785375,2.915179,0.844103,0.542483,2.327103,0.140539,0.074178
3,01BR010,NaN,Negative,Negative,7.315216,3.760213,2.620761,10.594133,0.677308,0.784480,3.277880,0.915829,0.598315,2.470557,0.139408,0.071651
4,01BR015,Negative,Positive,Positive,6.651519,3.611638,2.503401,10.167881,0.680488,0.779407,2.976329,0.883960,0.567833,2.404240,0.140040,0.073923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,21BR001,NaN,Negative,Negative,8.454276,3.980617,2.846619,11.321637,0.658405,0.795162,3.702810,0.959601,0.638428,2.615494,0.140919,0.071121
115,21BR002,NaN,Positive,Positive,7.192392,3.676996,2.623789,10.420849,0.663396,0.797131,3.359015,0.913664,0.622664,2.520486,0.138284,0.066163
116,21BR010,Negative,Positive,Positive,7.653298,3.799822,2.686248,10.770235,0.669009,0.785739,3.742968,0.973216,0.678134,2.723656,0.142631,0.072962
117,22BR005,Positive,Positive,Positive,7.369211,3.728282,2.657326,10.593930,0.660554,0.792731,3.274181,0.900226,0.589171,2.438282,0.141493,0.068355
118,22BR006,Negative,Positive,Positive,4.674415,2.999797,2.147106,8.528905,0.653925,0.785593,1.959682,0.705482,0.422107,1.902809,0.144684,0.081118