In [1]:
#### ------------------------------------------------------------------------------------------
#### author: Ranjan Barman, date: Jun 2, 2025
#### Mapped CPTAC HoverNet Immune-Only NPIFs (all tiles) to TCGA_BRCA subtype status
#### --------------------------------------------------------------------------------------------

import os
import pandas as pd

# Set working directory
_wpath_ = "/data/Lab_ruppin/Ranjan/HnE/"
os.chdir(_wpath_)
print(f"Working directory: {_wpath_}\n")

# Define dataset name and file paths
dataset_name = "CPTAC_BRCA"

# File paths for immune-only NPIFs and clinical subtypes
CPTAC_BRCA_ImmuneOnly_NPIFs_file = f"{dataset_name}/HoverNet/outputs/CPTAC_BRCA_HoverNet_ImmuneOnly_NPIFs.csv"
CPTAC_subtypes_file = "/data/Lab_ruppin/dhrubas2/HnE/CPTAC_BRCA/processed/CPTAC_BRCA_clinical_data_summary_matched.tsv"

# Load the immune-only NPIFs data
CPTAC_BRCA_ImmuneOnly_NPIFs = pd.read_csv(CPTAC_BRCA_ImmuneOnly_NPIFs_file)
CPTAC_BRCA_ImmuneOnly_NPIFs.columns = CPTAC_BRCA_ImmuneOnly_NPIFs.columns.str.strip()

# Load the clinical subtypes data
CPTAC_subtypes_data = pd.read_table(CPTAC_subtypes_file, sep="\t")
CPTAC_subtypes_data = CPTAC_subtypes_data[["Patient_ID", "HER2_status", "PR_status", "ER_status"]]
CPTAC_subtypes_data = CPTAC_subtypes_data.rename(columns={
    "HER2_status": "HER2_Status",
    "PR_status": "PR_Status",
    "ER_status": "ER_Status"
})

# Convert and pad patient IDs
CPTAC_subtypes_data["Patient_ID"] = CPTAC_subtypes_data["Patient_ID"].astype(str).str.zfill(3)

CPTAC_BRCA_ImmuneOnly_NPIFs
CPTAC_subtypes_data

Working directory: /data/Lab_ruppin/Ranjan/HnE/

    Patient_ID HER2_Status PR_Status ER_Status
0      01BR001    Negative  Negative  Negative
1      01BR008         NaN       NaN       NaN
2      01BR009         NaN  Negative  Negative
3      01BR010         NaN  Negative  Negative
4      01BR015    Negative  Positive  Positive
..         ...         ...       ...       ...
114    21BR001         NaN  Negative  Negative
115    21BR002         NaN  Positive  Positive
116    21BR010    Negative  Positive  Positive
117    22BR005    Positive  Positive  Positive
118    22BR006    Negative  Positive  Positive

[119 rows x 4 columns]

In [2]:
# Print debug info
print("Patient_IDs from CPTAC_BRCA_HoverNet_ImmuneOnly_NPIFs (Total: {}):".format(len(CPTAC_BRCA_ImmuneOnly_NPIFs)))
print(CPTAC_BRCA_ImmuneOnly_NPIFs["Patient_ID"].unique())

print("\nPatient IDs from CPTAC_subtypes_data (Total: {}):".format(len(CPTAC_subtypes_data)))
print(CPTAC_subtypes_data["Patient_ID"].unique())

# Identify non-matching IDs
slide_names = set(CPTAC_BRCA_ImmuneOnly_NPIFs["Patient_ID"])
patient_ids = set(CPTAC_subtypes_data["Patient_ID"])
non_matching_slides = slide_names - patient_ids
non_matching_patients = patient_ids - slide_names

print("\nImmune-Only NPIFs that do NOT have a matching Patient_ID:")
print(non_matching_slides)
print("\nBRCA subtypes that do NOT have a matching Patient_ID:")
print(non_matching_patients)

Patient_IDs from CPTAC_BRCA_HoverNet_ImmuneOnly_NPIFs (Total: 198):
['01BR001' '01BR002' '01BR003' '01BR004' '01BR005' '01BR006' '01BR007'
 '01BR008' '01BR009' '01BR010' '01BR011' '01BR012' '01BR013' '01BR014'
 '01BR015' '01BR016' '01BR017' '01BR018' '01BR019' '01BR020' '01BR021'
 '01BR022' '01BR023' '01BR024' '01BR025' '01BR026' '01BR027' '01BR028'
 '01BR029' '01BR030' '01BR031' '01BR032' '01BR033' '01BR034' '01BR039'
 '01BR040' '01BR041' '01BR042' '01BR043' '03BR002' '03BR004' '03BR005'
 '03BR006' '03BR008' '03BR009' '03BR010' '03BR011' '03BR012' '03BR013'
 '03BR014' '05BR001' '05BR002' '05BR003' '05BR004' '05BR005' '05BR009'
 '05BR010' '05BR015' '05BR016' '05BR019' '05BR022' '05BR024' '05BR026'
 '05BR029' '05BR031' '05BR032' '05BR033' '05BR038' '05BR040' '05BR042'
 '05BR043' '05BR044' '05BR045' '06BR003' '06BR005' '06BR006' '06BR009'
 '06BR014' '09BR001' '09BR002' '09BR004' '09BR005' '09BR007' '11BR003'
 '11BR004' '11BR005' '11BR006' '11BR009' '11BR010' '11BR011' '11BR012'
 '11BR013' '11BR014' '11BR015' '11BR016' '11BR017' '11BR018' '11BR019'
 '11BR020' '11BR021' '11BR022' '11BR023' '11BR024' '11BR025' '11BR027'
 '11BR028' '11BR029' '11BR030' '11BR031' '11BR032' '11BR033' '11BR034'
 '11BR035' '11BR036' '11BR037' '11BR038' '11BR040' '11BR041' '11BR042'
 '11BR043' '11BR044' '11BR047' '11BR048' '11BR049' '11BR050' '11BR051'
 '11BR052' '11BR053' '11BR054' '11BR055' '11BR056' '11BR057' '11BR058'
 '11BR059' '11BR060' '11BR069' '11BR072' '11BR073' '11BR074' '11BR075'
 '11BR076' '11BR077' '11BR078' '11BR079' '11BR080' '13BR003' '13BR004'
 '13BR009' '14BR002' '14BR005' '14BR007' '14BR008' '14BR011' '14BR012'
 '14BR014' '14BR020' '14BR023' '15BR001' '15BR002' '15BR003' '15BR004'
 '15BR011' '16BR012' '18BR001' '18BR002' '18BR003' '18BR004' '18BR005'
 '18BR006' '18BR007' '18BR008' '18BR009' '18BR010' '18BR016' '18BR017'
 '18BR019' '18BR020' '20BR001' '20BR002' '20BR003' '20BR004' '20BR005'
 '20BR006' '20BR007' '20BR008' '21BR001' '21BR002' '21BR003' '21BR005'
 '21BR010' '22BR001' '22BR002' '22BR003' '22BR005' '22BR006' '22BR007'
 '22BR008' '27BR002']

Patient IDs from CPTAC_subtypes_data (Total: 119):
['01BR001' '01BR008' '01BR009' '01BR010' '01BR015' '01BR017' '01BR018'
 '01BR020' '01BR023' '01BR025' '01BR026' '01BR027' '01BR030' '01BR031'
 '01BR032' '01BR033' '01BR040' '01BR042' '01BR043' '03BR002' '03BR004'
 '03BR006' '03BR010' '03BR011' '03BR013' '05BR001' '05BR003' '05BR004'
 '05BR005' '05BR009' '05BR016' '05BR026' '05BR029' '05BR038' '05BR042'
 '05BR043' '05BR044' '05BR045' '06BR003' '06BR005' '06BR006' '06BR014'
 '09BR001' '09BR004' '09BR005' '09BR007' '11BR003' '11BR004' '11BR006'
 '11BR009' '11BR010' '11BR011' '11BR012' '11BR013' '11BR014' '11BR015'
 '11BR016' '11BR017' '11BR018' '11BR019' '11BR020' '11BR022' '11BR023'
 '11BR024' '11BR025' '11BR027' '11BR028' '11BR030' '11BR031' '11BR032'
 '11BR036' '11BR038' '11BR040' '11BR042' '11BR043' '11BR044' '11BR047'
 '11BR049' '11BR050' '11BR051' '11BR053' '11BR054' '11BR055' '11BR056'
 '11BR058' '11BR059' '11BR060' '11BR072' '11BR073' '11BR074' '11BR075'
 '11BR080' '13BR009' '14BR005' '14BR008' '14BR014' '15BR003' '16BR012'
 '18BR002' '18BR003' '18BR004' '18BR006' '18BR007' '18BR009' '18BR010'
 '18BR016' '18BR017' '18BR019' '20BR001' '20BR002' '20BR005' '20BR006'
 '20BR007' '20BR008' '21BR001' '21BR002' '21BR010' '22BR005' '22BR006']

Immune-Only NPIFs that do NOT have a matching Patient_ID:
{'22BR002', '14BR012', '11BR033', '01BR007', '01BR021', '11BR005', '20BR003', '21BR003', '05BR031', '01BR039', '11BR078', '01BR041', '11BR079', '11BR029', '18BR008', '05BR019', '11BR077', '09BR002', '03BR012', '05BR010', '01BR003', '14BR002', '15BR011', '11BR057', '20BR004', '03BR008', '11BR069', '05BR040', '22BR003', '06BR009', '01BR016', '01BR012', '14BR023', '01BR028', '05BR033', '22BR001', '11BR052', '03BR014', '11BR037', '11BR021', '05BR024', '01BR002', '15BR004', '01BR029', '05BR032', '11BR048', '01BR013', '01BR022', '11BR076', '27BR002', '01BR019', '01BR024', '11BR041', '14BR011', '03BR009', '01BR004', '11BR035', '15BR002', '05BR002', '22BR008', '05BR022', '21BR005', '01BR011', '05BR015', '18BR001', '14BR020', '13BR003', '15BR001', '22BR007', '11BR034', '01BR005', '18BR005', '01BR034', '14BR007', '01BR014', '18BR020', '03BR005', '01BR006', '13BR004'}

BRCA subtypes that do NOT have a matching Patient_ID:
set()

In [3]:
# Merge data
merged_df = pd.merge(CPTAC_subtypes_data, CPTAC_BRCA_ImmuneOnly_NPIFs, on='Patient_ID', how="inner")

# Save output
output_path = f"{dataset_name}/outputs/HoverNet/Subtypes/"
os.makedirs(output_path, exist_ok=True)
output_file = os.path.join(output_path, "HoverNet_ImmuneOnly_NPIFs_All_Tiles_CPTAC_BRCA_Mapped_BRCA_Status.csv")
merged_df.to_csv(output_file, index=False)

print(f"Mapped immune-only NPIF data saved to: {output_file}")
print("Done!")

merged_df

Mapped immune-only NPIF data saved to: CPTAC_BRCA/outputs/HoverNet/Subtypes/HoverNet_ImmuneOnly_NPIFs_All_Tiles_CPTAC_BRCA_Mapped_BRCA_Status.csv
Done!

,Patient_ID,HER2_Status,PR_Status,ER_Status,Mean Area,Mean Major Axis,Mean Minor Axis,Mean Perimeter,Mean Eccentricity,Mean Circularity,Std Area,Std Major Axis,Std Minor Axis,Std Perimeter,Std Eccentricity,Std Circularity
0,01BR001,Negative,Negative,Negative,7.625997,3.787263,2.722527,10.771633,0.653359,0.790338,3.555293,0.950318,0.630684,2.575763,0.145582,0.068284
1,01BR008,NaN,NaN,NaN,6.469327,3.446697,2.520323,9.855064,0.637906,0.803826,3.081828,0.873608,0.570784,2.406561,0.144760,0.069092
2,01BR009,NaN,Negative,Negative,6.723080,3.558550,2.561321,10.153485,0.653102,0.788188,2.972786,0.850353,0.555833,2.331860,0.143270,0.071211
3,01BR010,NaN,Negative,Negative,7.132706,3.717920,2.588639,10.470122,0.677499,0.783510,3.290702,0.921041,0.602887,2.487643,0.140573,0.072371
4,01BR015,Negative,Positive,Positive,6.636145,3.606256,2.501840,10.143018,0.679801,0.781493,2.966967,0.883822,0.564953,2.383188,0.140158,0.073805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,21BR001,NaN,Negative,Negative,8.137908,3.891708,2.797739,11.073610,0.654031,0.796694,3.724825,0.972686,0.647281,2.665581,0.141853,0.070883
115,21BR002,NaN,Positive,Positive,6.965969,3.620355,2.589318,10.246660,0.660246,0.798334,3.286613,0.910456,0.613414,2.479450,0.140037,0.065675
116,21BR010,Negative,Positive,Positive,7.500161,3.770161,2.656366,10.656746,0.671548,0.786504,3.682186,0.974214,0.671003,2.694779,0.141353,0.072732
117,22BR005,Positive,Positive,Positive,7.218849,3.688916,2.640166,10.482135,0.657364,0.794211,3.221034,0.892752,0.585841,2.409777,0.141812,0.066819
118,22BR006,Negative,Positive,Positive,4.782527,3.028750,2.167473,8.614594,0.655039,0.785052,2.088553,0.721420,0.445609,1.961325,0.143788,0.077641